apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: koreflow
spec:
  selector:
    matchLabels:
      app: koreflow
  serviceName: "koreflow-headless"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: koreflow
    spec:
      containers:
      - name: koreflow
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

