apiVersion: v1
kind: Service
metadata:
  name: koreflow-external
spec:
  type: {{ .Values.service.type }}
  selector:
    app: koreflow
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
