---
# זהו קובץ המשימות עבור התפקיד 'demo_environment'.
# ההגדרות כמו hosts, become, remote_user מגיעות מהפלייבוק הראשי שקורא לתפקיד זה.

- name: Wait for SSH connection to be established
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 600
  tags:
    - always # Ensure this always runs, even if specific tags are used

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
  become: yes # Ensure this runs with sudo
  tags:
    - setup

- name: Install docker.io package
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes # Ensure this runs with sudo
  tags:
    - docker

- name: Ensure Docker service is running and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes # Ensure this runs with sudo
  tags:
    - docker

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: yes
  tags:
    - docker

- name: Add 'ubuntu' user to the 'docker' group
  ansible.builtin.user:
    name: ubuntu # Assuming 'ubuntu' is the remote_user for this role
    groups: docker
    append: yes
  become: yes
  tags:
    - docker

- name: Restart sshd to apply new group membership for 'ubuntu' user
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes
  ignore_errors: true # Ignore potential temporary connection issues during restart
  tags:
    - docker

- name: Pause for 10 seconds to allow group changes to propagate and sshd to restart fully
  ansible.builtin.pause:
    seconds: 10
    prompt: "Pausing for 10 seconds for group changes to apply..."
  tags:
    - docker

- name: Docker login to Docker Hub
  community.docker.docker_login:
    username: "{{ lookup('env', 'DOCKER_USER') }}"
    password: "{{ lookup('env', 'DOCKER_PASS') }}"
    registry_url: https://index.docker.io/v1/ # <-- השינוי כאן! מ-server_url ל-registry_url
  become: yes
  register: docker_login_result

# המשימה הבאה מציגה את תוצאות הלוגין רק אם הוא נכשל
- name: Debug Docker login result on failure
  ansible.builtin.debug:
    var: docker_login_result
  when: docker_login_result is failed
  tags:
    - docker
    - deploy

- name: Pull the specified Docker image
  community.docker.docker_image:
    name: barhe2/taskomatic
    tag: latest
    source: pull
  become: yes # Ensure this runs with sudo as well
  tags:
    - deploy

- name: Run the Docker container
  community.docker.docker_container:
    name: taskomatic-app
    image: barhe2/taskomatic:latest
    state: started
    recreate: yes
    ports:
      - "80:80"
    restart_policy: always
  become: yes # Ensure this runs with sudo
  tags:
    - deploy

# - name: Pause for 300 seconds (5 minutes)
#   ansible.builtin.pause:
#     seconds: 300
#     prompt: "Pausing for 5 minutes before shutdown..."
#   tags:
#     - cleanup

# - name: Gracefully shut down the instance
#   ansible.builtin.command: /sbin/shutdown -h now
#   async: 1
#   poll: 0
#   ignore_errors: true
#   become: yes # Ensure shutdown command runs with sudo
#   tags:
#     - cleanup